version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build: ./backend/django_app
    container_name: web
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 sentiment_project.asgi:application"
    volumes:
      - ./backend/django_app:/app
      - ./frontend:/frontend:ro
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      REDIS_HOST: redis
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      GROQ_API_KEY: ${GROQ_API_KEY}
      FRONTEND_DIR: /frontend
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: ./backend/worker
    container_name: worker
    command: python worker.py
    volumes:
      - ./backend/worker:/app
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      REDIS_HOST: redis
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
